version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.5
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: iotclima
      POSTGRES_PASSWORD: iotclima
    ports:
      - 5439:5432
volumes:
  pgdata:
