# Generated by Django 5.2.3 on 2025-06-15 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('installed_date', models.DateTimeField(blank=True, null=True)),
                ('removed_date', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('calibrated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_sensor_links', to='sensors.sensor')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_sensor_links', to='stations.station')),
            ],
            options={
                'unique_together': {('station', 'sensor')},
            },
        ),
    ]
