# http/v1_events.http

@baseUrl = http://localhost:3333/api/v1
@events_id = 1

### List all events
GET {baseUrl}/events/

### Create a new events
POST {baseUrl}/events/
Content-Type: application/json

{
  "name": "Sample events name"
}

### Retrieve a events by ID
GET {baseUrl}/events/{{events_id}}/

### Update a events by ID (PUT)
PUT {baseUrl}/events/{{events_id}}/
Content-Type: application/json

{
  "name": "Updated events name"
}

### Partially update a events by ID (PATCH)
PATCH {baseUrl}/events/{{events_id}}/
Content-Type: application/json

{
  "name": "Partial update of events name"
}

### Delete a events by ID
DELETE {baseUrl}/events/{{events_id}}/
