# http/v1_sensors.http

@baseUrl = http://localhost:3333/api/v1
@sensors_id = 1

### List all sensors
GET {baseUrl}/sensors/

### Create a new sensors
POST {baseUrl}/sensors/
Content-Type: application/json

{
  "name": "Sample sensors name"
}

### Retrieve a sensors by ID
GET {baseUrl}/sensors/{{sensors_id}}/

### Update a sensors by ID (PUT)
PUT {baseUrl}/sensors/{{sensors_id}}/
Content-Type: application/json

{
  "name": "Updated sensors name"
}

### Partially update a sensors by ID (PATCH)
PATCH {baseUrl}/sensors/{{sensors_id}}/
Content-Type: application/json

{
  "name": "Partial update of sensors name"
}

### Delete a sensors by ID
DELETE {baseUrl}/sensors/{{sensors_id}}/
