# Generated by Django 5.2.3 on 2025-06-15 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('model', models.CharField(max_length=255)),
                ('unit', models.IntegerField(choices=[(1, 'Celsius'), (2, 'Fahrenheit'), (3, 'Percent'), (4, 'Meters/Second'), (5, 'Kilometers/Hour'), (6, 'Hectopascal'), (7, 'Millimeters'), (8, 'Other Unit')])),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('type', models.IntegerField(choices=[(1, 'Temperature'), (2, 'Humidity'), (3, 'Wind'), (4, 'Pressure'), (5, 'Rainfall'), (6, 'Other')])),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Error')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
