# Generated by Django 5.2.3 on 2025-06-15 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('model', models.CharField(max_length=255)),
                ('firmware', models.CharField(blank=True, max_length=255, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('last_maintenance_at', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance_at', models.DateTimeField(blank=True, null=True)),
                ('battery_level', models.IntegerField(blank=True, null=True)),
                ('signal_strength', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (2, 'Online'), (3, 'Offline'), (4, 'Maintenance')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='places.place')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
