# Generated by Django 5.2.3 on 2025-06-16 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('station_sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='station',
        ),
        migrations.AddField(
            model_name='event',
            name='station_sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='station_sensors.stationsensor'),
        ),
    ]
